version: '3.2'

services:
  api:
    build:
      context: .
      dockerfile: ./hivemind/Dockerfile
    env_file: ./.env.docker
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    restart: on-failure
    networks:
      - backend

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    env_file: ./.env.docker
    deploy:
      replicas: 1
    ports:
      - target: 3030
        published: 3030
        protocol: tcp
        mode: ingress
    restart: always
    networks:
      - backend
    
  redis:
    image: redis:latest
    deploy:
      replicas: 1
    restart: unless-stopped
    networks:
      - backend


networks:
  backend:

